****************** DOC PRONTUARIO *******************
SELECT * FROM DOCUMENTO                        -- DOCUMENTOS DE PRONTUARIOS
SELECT * FROM REGISTRO_DOCUMENTO               -- QUANTIDADE DE VEZES QUE FOI PREENCHIDO
SELECT * FROM REGISTRO_RESPOSTA                -- RESPOSTA DO DOCUMENTO
SELECT * FROM VDIC_RESPOSTA_DOCUMENTO          -- MOSTRA QUEM PREENCHEU O DOCUMENTO E A DATA
SELECT * FROM VDIC_ITEM_RESPOSTA_DOCUMENTO     -- MOSTRA AS RESPOSTAS PREENCHIDAS NOS DOCUMENTOS
SELECT * FROM DOCUMENTO_OBRIGATORIO            -- ITEM DE PRESCRIÇÃO QUE O DOCUMENTO É OBRIGATÓRIO
SELECT * FROM DOCUMENTO_ACAO                   -- AÇÃO QUE O DOCUMENTO REALIZA NO BANCO QUANDO É PREENCHIDO
SELECT * FROM GRUPO_PERGUNTA                   -- MOSTRA AS PERGUNTAS DE CADA DOCUMENTO
SELECT * FROM GRUPO_PERGUNTA_DOC               -- MOSTRA AS CONFIGURAÇÕES DA PERGUNTA
SELECT * FROM PERGUNTA_DOC                     -- NOME DA PERGUNTA + IDENTIFICAÇÃO