SELECT SUM(TOTAL) FROM(
SELECT DS_FILA,
        SUM(TOTAL) TOTAL FROM(
SELECT TO_CHAR(S1.DH_PROCESSO,'DD/MM/YYYY') DATA ,TA.CD_TRIAGEM_ATENDIMENTO,TA.DS_SENHA, FS.DS_FILA, COUNT(*) TOTAL 
FROM SACR_TEMPO_PROCESSO S1,
     TRIAGEM_ATENDIMENTO TA,
     FILA_SENHA FS
WHERE TA.CD_TRIAGEM_ATENDIMENTO = S1.CD_TRIAGEM_ATENDIMENTO
AND TA.CD_MULTI_EMPRESA = 1
AND TA.DH_PRE_ATENDIMENTO BETWEEN '26-06-2015' AND '27-06-2015'
AND S1.CD_TIPO_TEMPO_PROCESSO = 1
AND TA.CD_FILA_SENHA = FS.CD_FILA_SENHA
AND TA.DH_REMOVIDO IS NULL
GROUP BY S1.DH_PROCESSO,TA.CD_TRIAGEM_ATENDIMENTO, TA.DS_SENHA, FS.DS_FILA
ORDER BY TA.CD_TRIAGEM_ATENDIMENTO
)
GROUP BY DS_FILA
)

SELECT * FROM SACR_TEMPO_PROCESSO

SELECT SUM(TOTAL) FROM(
SELECT CD_TRIAGEM_ATENDIMENTO, COUNT(*) TOTAL FROM TRIAGEM_ATENDIMENTO WHERE CD_MULTI_EMPRESA = 1
AND DH_PRE_ATENDIMENTO BETWEEN '29-06-2015' AND '30-06-2015'
GROUP BY CD_TRIAGEM_ATENDIMENTO
)

SELECT * FROM TRIAGEM_ATENDIMENTO WHERE CD_MULTI_EMPRESA = 1
AND DH_PRE_ATENDIMENTO BETWEEN '26-06-2015' AND '27-06-2015'

SELECT * FROM FILA_SENHA WHERE CD_MULTI_EMPRESA = 1