SELECT CASE
  WHEN P.NM_SOCIAL_PACIENTE IS NOT NULL THEN
    (SELECT P.NM_SOCIAL_PACIENTE FROM PACIENTE P, ATENDIME A WHERE A.CD_PACIENTE = P.CD_PACIENTE AND A.CD_ATENDIMENTO = &<CD_ATENDIMENTO>)
  WHEN P.NM_SOCIAL_PACIENTE IS NULL THEN
    (SELECT P.NM_PACIENTE FROM PACIENTE P, ATENDIME A WHERE A.CD_PACIENTE = P.CD_PACIENTE AND A.CD_ATENDIMENTO = &<CD_ATENDIMENTO>)
  ELSE
    (SELECT P.NM_PACIENTE FROM PACIENTE P, ATENDIME A WHERE A.CD_PACIENTE = P.CD_PACIENTE AND A.CD_ATENDIMENTO = &<CD_ATENDIMENTO>)
    END AS NOME
  FROM PACIENTE P,
       ATENDIME A
  WHERE A.CD_PACIENTE = P.CD_PACIENTE
  AND A.CD_ATENDIMENTO = &<CD_ATENDIMENTO>