SELECT SUBSTR(TELEFONE,3),
       CD_PACIENTE,
       NM_PACIENTE,
       NM_SOCIAL,
       DT_AGENDA,
       HORA,
       NM_PRESTADOR,
       DS_ITEM_AGENDAMENTO,
       DS_TIP_MAR
FROM(
SELECT TELEFONE,
       CD_PACIENTE,
       NM_PACIENTE,
       NM_SOCIAL,
       DT_AGENDA,
       HORA,
       NM_PRESTADOR,
       DS_ITEM_AGENDAMENTO,
       DS_TIP_MAR
FROM(
SELECT CON.NR_DDD || CON.NR_TELEFONE TELEFONE,
       IT.CD_PACIENTE,
       IT.NM_PACIENTE,
       (SELECT NM_SOCIAL_PACIENTE FROM PACIENTE WHERE CD_PACIENTE = IT.CD_PACIENTE) NM_SOCIAL,
       TO_CHAR(AC.DT_AGENDA,'DD/MM/YYYY') DT_AGENDA,
       TO_CHAR(IT.HR_AGENDA,'HH24:MI') HORA,
       PRE.NM_PRESTADOR,
       ITEM.DS_ITEM_AGENDAMENTO,
       TP.DS_TIP_MAR
FROM AGENDA_CENTRAL AC,
     IT_AGENDA_CENTRAL IT,
     PRESTADOR PRE,
     ITEM_AGENDAMENTO ITEM,
     TIP_MAR TP,
     CONTATO_PACIENTE CON
WHERE AC.DT_AGENDA BETWEEN '01-03-2016' AND '31-03-2016'
AND IT.CD_AGENDA_CENTRAL = AC.CD_AGENDA_CENTRAL
AND AC.CD_MULTI_EMPRESA = 1
AND AC.TP_AGENDA = 'A'
AND IT.CD_TIP_MAR = 2
AND IT.CD_ITEM_AGENDAMENTO = ITEM.CD_ITEM_AGENDAMENTO
AND PRE.CD_PRESTADOR = AC.CD_PRESTADOR
AND IT.CD_TIP_MAR = TP.CD_TIP_MAR
AND CON.CD_PACIENTE = IT.CD_PACIENTE
AND CON.TP_CONTATO = 'C' 
AND CON.SN_PADRAO = 'S'
AND IT.CD_PACIENTE IS NOT NULL
)
WHERE TELEFONE IS NOT NULL AND TELEFONE <> '-'

UNION ALL

SELECT TELEFONE,
       CD_PACIENTE,
       NM_PACIENTE,
       NM_SOCIAL,
       DT_AGENDA,
       HORA,
       NM_PRESTADOR,
       DS_ITEM_AGENDAMENTO,
       DS_TIP_MAR
FROM(
SELECT CON.NR_DDD || CON.NR_TELEFONE TELEFONE,
       IT.CD_PACIENTE,
       IT.NM_PACIENTE,
       (SELECT NM_SOCIAL_PACIENTE FROM PACIENTE WHERE CD_PACIENTE = IT.CD_PACIENTE) NM_SOCIAL,
       TO_CHAR(AC.DT_AGENDA,'DD/MM/YYYY') DT_AGENDA,
       TO_CHAR(IT.HR_AGENDA,'HH24:MI') HORA,
       PRE.NM_PRESTADOR,
       ITEM.DS_ITEM_AGENDAMENTO,
       TP.DS_TIP_MAR
FROM AGENDA_CENTRAL AC,
     IT_AGENDA_CENTRAL IT,
     PRESTADOR PRE,
     ITEM_AGENDAMENTO ITEM,
     TIP_MAR TP,
     CONTATO_PACIENTE CON
WHERE AC.DT_AGENDA BETWEEN '01-03-2016' AND '31-03-2016'
AND IT.CD_AGENDA_CENTRAL = AC.CD_AGENDA_CENTRAL
AND AC.CD_MULTI_EMPRESA = 1
AND AC.TP_AGENDA = 'A'
AND IT.CD_TIP_MAR = 2
AND IT.CD_ITEM_AGENDAMENTO = ITEM.CD_ITEM_AGENDAMENTO
AND PRE.CD_PRESTADOR = AC.CD_PRESTADOR
AND IT.CD_TIP_MAR = TP.CD_TIP_MAR
AND CON.CD_PACIENTE = IT.CD_PACIENTE
AND CON.TP_CONTATO = 'R' 
AND CON.SN_PADRAO = 'S'
AND IT.CD_PACIENTE IS NOT NULL
)
WHERE CD_PACIENTE NOT IN(
SELECT IT.CD_PACIENTE
FROM AGENDA_CENTRAL AC,
     IT_AGENDA_CENTRAL IT,
     PRESTADOR PRE,
     ITEM_AGENDAMENTO ITEM,
     TIP_MAR TP,
     CONTATO_PACIENTE CON
WHERE AC.DT_AGENDA BETWEEN '01-03-2016' AND '31-03-2016'
AND IT.CD_AGENDA_CENTRAL = AC.CD_AGENDA_CENTRAL
AND AC.CD_MULTI_EMPRESA = 1
AND AC.TP_AGENDA = 'A'
AND IT.CD_TIP_MAR = 2
AND IT.CD_ITEM_AGENDAMENTO = ITEM.CD_ITEM_AGENDAMENTO
AND PRE.CD_PRESTADOR = AC.CD_PRESTADOR
AND IT.CD_TIP_MAR = TP.CD_TIP_MAR
AND CON.CD_PACIENTE = IT.CD_PACIENTE
AND CON.TP_CONTATO = 'C' 
AND CON.SN_PADRAO = 'S'
AND IT.CD_PACIENTE IS NOT NULL
)
AND TELEFONE IS NOT NULL AND TELEFONE <> '-'
)ORDER BY DT_AGENDA,HORA, NM_PRESTADOR