SELECT * FROM LOG_EXCLUSAO_AGENDAMENTO
WHERE CD_MULTI_EMPRESA = 1
ORDER BY CD_LOG_EXCLUSAO_AGENDAMENTO DESC


SELECT * FROM ALL_TABLES WHERE TABLE_NAME LIKE 'LOG%' AND OWNER NOT IN('SYSTEM','SYS') ORDER BY TABLE_NAME

SELECT * FROM log_opera_agenda_central ORDER BY 1 DESC

