SELECT CD_ATENDIMENTO, CD_LOC_PROCED,TP_ATENDIMENTO FROM ATENDIME
WHERE CD_MULTI_EMPRESA = 1
AND DT_ATENDIMENTO BETWEEN '10-09-2014' AND '10-09-2014'

SELECT LP.DS_LOC_PROCED,
       P.NM_PACIENTE
 FROM ATENDIME A,
      PACIENTE P,
      LOC_PROCED LP
WHERE A.CD_ATENDIMENTO = 2952507
AND LP.CD_LOC_PROCED = A.CD_LOC_PROCED
AND A.CD_PACIENTE = P.CD_PACIENTE


SELECT DS_LOC_PROCED FROM LOC_PROCED WHERE CD_LOC_PROCED = 27

SELECT * FROM IT_AGENDA_CENTRAL


SELECT DS_LOC_PROCED,
       Sum(ENCAMINHADOS) ENCAMINHADOS,
       Sum(atendidos) ATENDIDOS
       FROM(
SELECT AC.CD_AGENDA_CENTRAL,
       IT.CD_ATENDIMENTO,
       AC.DT_AGENDA,
       IT.SN_ATENDIDO,
       IT.CD_PACIENTE,
       IT.SN_ENCAIXE,
       IT.CD_TIP_MAR,
       LP.CD_LOC_PROCED,
       LP.DS_LOC_PROCED,
       Count(*) ENCAMINHADOS,
       0 ATENDIDOS
FROM IT_AGENDA_CENTRAL IT,
     AGENDA_CENTRAL AC,
     ATENDIME A,
     LOC_PROCED LP
WHERE To_Date(AC.DT_AGENDA,'DD/MM/YYYY') BETWEEN To_Date(:DT_INCIAL,'DD/MM/YYYY') AND To_Date(:DT_FINAL,'DD/MM/YYYY')
AND AC.CD_AGENDA_CENTRAL = IT.CD_AGENDA_CENTRAL
AND IT.CD_ATENDIMENTO = A.CD_ATENDIMENTO
AND A.CD_LOC_PROCED = LP.CD_LOC_PROCED
AND AC.CD_MULTI_EMPRESA = 1
AND AC.TP_AGENDA = 'A'
AND IT.CD_PACIENTE IS NOT NULL
AND IT.CD_TIP_MAR = 1
AND A.CD_LOC_PROCED NOT IN(27)
GROUP BY AC.CD_AGENDA_CENTRAL,
      IT.CD_ATENDIMENTO,
      AC.DT_AGENDA,
      IT.SN_ATENDIDO,
      IT.CD_PACIENTE,
      IT.SN_ENCAIXE,
      IT.CD_TIP_MAR,
      LP.CD_LOC_PROCED,
      LP.DS_LOC_PROCED

UNION ALL

SELECT AC.CD_AGENDA_CENTRAL,
       IT.CD_ATENDIMENTO,
       AC.DT_AGENDA,
       IT.SN_ATENDIDO,
       IT.CD_PACIENTE,
       IT.SN_ENCAIXE,
       IT.CD_TIP_MAR,
       LP.CD_LOC_PROCED,
       LP.DS_LOC_PROCED,
       0 ENCAMINHADOS,
       Count(*) ATENDIDOS
FROM IT_AGENDA_CENTRAL IT,
     AGENDA_CENTRAL AC,
     ATENDIME A,
     LOC_PROCED LP
WHERE To_Date(AC.DT_AGENDA,'DD/MM/YYYY') BETWEEN To_Date(:DT_INCIAL,'DD/MM/YYYY') AND To_Date(:DT_FINAL,'DD/MM/YYYY')
AND AC.CD_AGENDA_CENTRAL = IT.CD_AGENDA_CENTRAL
AND IT.CD_ATENDIMENTO = A.CD_ATENDIMENTO
AND A.CD_LOC_PROCED = LP.CD_LOC_PROCED
AND AC.CD_MULTI_EMPRESA = 1
AND AC.TP_AGENDA = 'A'
AND IT.CD_PACIENTE IS NOT NULL
AND IT.CD_TIP_MAR = 1
AND A.CD_LOC_PROCED NOT IN(27)
AND IT.SN_ATENDIDO = 'S'
GROUP BY AC.CD_AGENDA_CENTRAL,
      IT.CD_ATENDIMENTO,
      AC.DT_AGENDA,
      IT.SN_ATENDIDO,
      IT.CD_PACIENTE,
      IT.SN_ENCAIXE,
      IT.CD_TIP_MAR,
      LP.CD_LOC_PROCED,
      LP.DS_LOC_PROCED
)
GROUP BY DS_LOC_PROCED
