SELECT NM_PRESTADOR,
       N_MES,
       MES,
       SUM(TOTAL)
       FROM(
SELECT P.NM_PRESTADOR,
       IT.CD_ATENDIMENTO,
       TO_CHAR(AC.DT_AGENDA,'MM') N_MES,
       DECODE(TO_CHAR(AC.DT_AGENDA,'MM'),'01','JANEIRO','02','FEVEREIRO','03','MARÇO','04','ABRIL','05','MAIO','06','JUNHO','07','JULHO','08','AGOSTO','09','SETEMBRO','10','OUTUBRO','11','NOVEMBRO','12','DEZEMBRO')MES,
       COUNT(*) TOTAL
      FROM IT_AGENDA_CENTRAL IT,
           AGENDA_CENTRAL AC,
           PRESTADOR P
      WHERE AC.CD_AGENDA_CENTRAL = IT.CD_AGENDA_CENTRAL
      AND AC.DT_AGENDA BETWEEN '01-01-2014' AND '31-10-2014'
      AND IT.SN_ATENDIDO = 'S'
      AND P.CD_PRESTADOR = AC.CD_PRESTADOR
      AND AC.CD_MULTI_EMPRESA = 1
      GROUP BY P.NM_PRESTADOR, IT.CD_ATENDIMENTO, AC.DT_AGENDA
      ORDER BY P.NM_PRESTADOR)
      GROUP BY NM_PRESTADOR, N_MES,MES
      ORDER BY NM_PRESTADOR, N_MES
      
SELECT * FROM AGENDA_cENTRAL