SELECT DESC_DOCUMENTO_PRONTUARIO,
       SUM(TOTAL)
       FROM(
SELECT VRD.REGISTRO_DOCUMENTO,
       VDP.DESC_DOCUMENTO_PRONTUARIO,
       VRD.USUARIO,
       VRD.DATA_REGISTRO,
       VRD.ATENDIMENTO,
       VRD.IMPRESSO, COUNT(*) TOTAL
FROM VDIC_RESPOSTA_DOCUMENTO VRD,
     VDIC_DOCUMENTO_PRONTUARIO VDP,
     ATENDIME A
WHERE DATA_REGISTRO BETWEEN '01-01-2014' AND '31-10-2014'
AND VRD.DOCUMENTO_PRONTUARIO = VDP.DOCUMENTO_PRONTUARIO
AND A.CD_ATENDIMENTO = VRD.ATENDIMENTO
AND A.CD_MULTI_EMPRESA = 1
GROUP BY VRD.REGISTRO_DOCUMENTO, VDP.DESC_DOCUMENTO_PRONTUARIO,VRD.USUARIO,VRD.DATA_REGISTRO,VRD.ATENDIMENTO,VRD.IMPRESSO
ORDER BY VRD.DATA_REGISTRO,VRD.ATENDIMENTO
)
GROUP BY DESC_DOCUMENTO_PRONTUARIO
ORDER BY DESC_DOCUMENTO_PRONTUARIO
