SELECT SER.DS_SER_DIS,
       MAR.DS_TIP_MAR,
       IT.SN_PUBLICO,
       Count(*) "N_IT"
  FROM IT_AGENDA_CENTRAL IT,
       AGENDA_CENTRAL AC,
       SER_DIS SER,
       TIP_MAR MAR
WHERE AC.DT_AGENDA_CENTRAL BETWEEN '10-07-2014' AND '10-07-2014'
      AND AC.CD_AGENDA_CENTRAL = IT.CD_AGENDA_CENTRAL
      AND IT.CD_SER_DIS = SER.CD_SER_DIS
      AND IT.CD_TIP_MAR = MAR.CD_TIP_MAR
GROUP BY SER.DS_SER_DIS, MAR.DS_TIP_MAR, IT.SN_PUBLICO

SELECT