SELECT IT.CD_AGENDA_CENTRAL CD_AGENDA,
       AC.CD_PRESTADOR CD_PRES,
       P.NM_PRESTADOR NM_PRES,
       DECODE(AC.TP_AGENDA,'A','Ambulatório','L','Laboratório','I','Imagem') TIPO,
       TO_CHAR(AC.DT_AGENDA,'DD/MM/YYYY') DATA_AGENDA,
       TO_CHAR(AC.DT_LIBERACAO)DATA_LIBERA, 
       TO_CHAR(AC.HR_INICIO,'HH24:MI')INICIO,
       TO_CHAR(AC.HR_FIM,'HH24:MI') FIM,
       TO_CHAR(IT.HR_AGENDA,'HH24:MI') HORARIO_INATIVO
FROM IT_AGENDA_CENTRAL IT,
     AGENDA_CENTRAL AC,
     PRESTADOR P
WHERE IT.SN_PUBLICO = 'N'
AND AC.CD_AGENDA_CENTRAL = IT.CD_AGENDA_CENTRAL
AND AC.CD_PRESTADOR = P.CD_PRESTADOR
AND TO_DATE(AC.DT_AGENDA,'DD/MM/YYYY') BETWEEN TO_DATE(:DT_INICIAL,'DD/MM/YYYY') AND TO_DATE(:DT_FINAL,'DD/MM/YYYY')
AND P.NM_PRESTADOR LIKE Decode(:NR_PRESTADOR,'TODOS','%',:NR_PRESTADOR)
ORDER BY 1,2,3,4,5,6,7,8,9 ASC


SELECT
      ser.ds_ser_dis,
      mar.ds_tip_mar, 
FROM
    dbamv.agenda_central ac,
    dbamv.it_agenda_central it,
    dbamv.tip_mar mar,
    dbamv.ser_dis ser
WHERE 
      ac.dt_agenda BETWEEN '10-07-2014' AND '10-07-2014'
      AND AC.CD_AGENDA_CENTRAL = IT.CD_AGENDA_CENTRAL
      AND IT.CD_TIP_MAR = MAR.CD_TIP_MAR
      AND AC.CD_MULTI_EMPRESA = 1
      AND IT.CD_SER_DIS = SER.CD_SER_DIS
      AND IT.CD_IT_AGENDA_PAI IS NULL


