SELECT *
FROM ATENDIME A
WHERE A.CD_ATENDIMENTO NOT IN(
  SELECT
    itage.CD_ATENDIMENTO,
    exa.ds_item_agendamento
FROM
    dbamv.item_agendamento exa,
    dbamv.agenda_central ac,
    dbamv.it_agenda_central itage
WHERE
    ac.dt_agenda BETWEEN '05-09-2014' AND '05-09-2014'
AND ac.cd_agenda_central = itage.cd_agenda_central(+)
AND itage.cd_item_agendamento = exa.cd_item_agendamento
AND ac.cd_multi_empresa = 1
AND exa.tp_item IN('I')
AND AC.CD_USUARIO != 'ACESSOPEP'
AND itage.CD_ATENDIMENTO IS NOT NULL
AND itage.SN_PUBLICO = 'S'
)
AND A.DT_ATENDIMENTO BETWEEN '05-09-2014' AND '05-09-2014'
AND A.CD_MULTI_EMPRESA = 1


SELECT TP.DS_TIP_MAR
FROM ATENDIME A,TIP_MAR TP
WHERE A.CD_ATENDIMENTO = 2944879
AND A.CD_TIP_MAR = TP.CD_TIP_MAR

SELECT * FROM TIP_MAR


SELECT * FROM PRESTADOR WHERE CD_PRESTADOR = 77

SELECT DS_ITEM_AGENDAMENTO
FROM ITEM_AGENDAMENTO
WHERE CD_ITEM_AGENDAMENTO IN(
SELECT DISTINCT(IT.CD_ITEM_AGENDAMENTO)
FROM
IT_AGENDA_CENTRAL IT
WHERE IT.CD_AGENDA_CENTRAL IN
(
SELECT AC.CD_AGENDA_CENTRAL
FROM AGENDA_CENTRAL AC
WHERE AC.CD_PRESTADOR = 77
AND AC.DT_AGENDA BETWEEN '05-09-2014' AND '05-09-2014'
AND AC.CD_USUARIO != 'ACESSOPEP'
)
AND IT.CD_ITEM_AGENDAMENTO IS NOT NULL
)



SELECT DISTINCT(CD_ITEM_AGENDAMENTO) FROM IT_AGENDA_CENTRAL WHERE CD_AGENDA_CENTRAL =  144557 AND CD_ITEM_AGENDAMENTO IS NOT NULL

SELECT * FROM ATENDIME WHERE CD_ATENDIMENTO = 2944641
SELECT * FROM IT_AGENDA_CENTRAL WHERE CD_ATENDIMENTO =