SELECT COUNT(ATE)
FROM(
SELECT DATA,HORA,MAR,ESP,PRE,ATE,TOTEM, CHAMADA_PAINEL,INICIO_RECEPCAO,FINAL_RECEPCAO,INICIO_MEDICO, FINAL_MEDICO FROM(
SELECT TO_CHAR(AC.DT_AGENDA,'DD/MM/YYYY') DATA,
       TO_CHAR(IT.HR_AGENDA,'HH24:MI') HORA,
       TP.DS_TIP_MAR MAR,
       E.DS_ESPECIALID ESP,
       P.NM_PRESTADOR PRE,
        A.CD_ATENDIMENTO ATE,
       (SELECT to_char(S1.DH_PROCESSO,'HH24:MI')FROM SACR_TEMPO_PROCESSO S1 WHERE S1.CD_ATENDIMENTO = A.CD_ATENDIMENTO AND S1.CD_TIPO_TEMPO_PROCESSO = 1) Totem,
       (SELECT to_char(S2.DH_PROCESSO,'HH24:MI')FROM SACR_TEMPO_PROCESSO S2 WHERE S2.CD_ATENDIMENTO = A.CD_ATENDIMENTO AND S2.CD_TIPO_TEMPO_PROCESSO = 20) Chamada_painel,
       (SELECT to_char(S3.DH_PROCESSO,'HH24:MI')FROM SACR_TEMPO_PROCESSO S3 WHERE S3.CD_ATENDIMENTO = A.CD_ATENDIMENTO AND S3.CD_TIPO_TEMPO_PROCESSO = 21) Inicio_Recepcao,
       (SELECT to_char(S4.DH_PROCESSO,'HH24:MI')FROM SACR_TEMPO_PROCESSO S4 WHERE S4.CD_ATENDIMENTO = A.CD_ATENDIMENTO AND S4.CD_TIPO_TEMPO_PROCESSO = 22) Final_Recepcao,
       (SELECT to_char(S5.DH_PROCESSO,'HH24:MI')FROM SACR_TEMPO_PROCESSO S5 WHERE S5.CD_ATENDIMENTO = A.CD_ATENDIMENTO AND S5.CD_TIPO_TEMPO_PROCESSO = 31) Inicio_Medico,
       TO_CHAR(A.HR_ALTA_MEDICA,'HH24:MI') Final_Medico
FROM ATENDIME A,
     IT_AGENDA_CENTRAL IT,
     AGENDA_CENTRAL AC,
     TIP_MAR TP,
     ESPECIALID E,
     PRESTADOR P
WHERE A.TP_ATENDIMENTO = 'A'
AND A.DT_ATENDIMENTO BETWEEN '01-01-2015' AND '30-04-2015'
AND A.CD_MULTI_EMPRESA = 1
AND A.CD_ATENDIMENTO = IT.CD_ATENDIMENTO
AND IT.CD_AGENDA_CENTRAL = AC.CD_AGENDA_CENTRAL
AND TP.CD_TIP_MAR = A.CD_TIP_MAR
AND A.CD_ESPECIALID = E.CD_ESPECIALID
AND P.CD_PRESTADOR = A.CD_PRESTADOR
AND IT.CD_IT_AGENDA_PAI IS NULL

UNION ALL

SELECT TO_CHAR(A2.DT_ATENDIMENTO,'DD/MM/YYYY') DATA,
       TO_CHAR(A2.HR_ATENDIMENTO,'HH24:MI') HORA,
       TP.DS_TIP_MAR,
       E.DS_ESPECIALID,
       P.NM_PRESTADOR PRE,
       A2.CD_ATENDIMENTO,
       (SELECT to_char(S1.DH_PROCESSO,'HH24:MI')FROM SACR_TEMPO_PROCESSO S1 WHERE S1.CD_ATENDIMENTO = A2.CD_ATENDIMENTO AND S1.CD_TIPO_TEMPO_PROCESSO = 1) Totem,
       (SELECT to_char(S2.DH_PROCESSO,'HH24:MI')FROM SACR_TEMPO_PROCESSO S2 WHERE S2.CD_ATENDIMENTO = A2.CD_ATENDIMENTO AND S2.CD_TIPO_TEMPO_PROCESSO = 20) Chamada_painel,
       (SELECT to_char(S3.DH_PROCESSO,'HH24:MI')FROM SACR_TEMPO_PROCESSO S3 WHERE S3.CD_ATENDIMENTO = A2.CD_ATENDIMENTO AND S3.CD_TIPO_TEMPO_PROCESSO = 21) Inicio_Recepcao,
       (SELECT to_char(S4.DH_PROCESSO,'HH24:MI')FROM SACR_TEMPO_PROCESSO S4 WHERE S4.CD_ATENDIMENTO = A2.CD_ATENDIMENTO AND S4.CD_TIPO_TEMPO_PROCESSO = 22) Final_Recepcao,
       (SELECT to_char(S5.DH_PROCESSO,'HH24:MI')FROM SACR_TEMPO_PROCESSO S5 WHERE S5.CD_ATENDIMENTO = A2.CD_ATENDIMENTO AND S5.CD_TIPO_TEMPO_PROCESSO = 31) Inicio_Medico,
       TO_CHAR(A2.HR_ALTA_MEDICA,'HH24:MI') Final_Medico
FROM ATENDIME A2, TIP_MAR TP, ESPECIALID E, PRESTADOR P
WHERE A2.CD_ATENDIMENTO NOT IN(
SELECT ATE
FROM(
SELECT A.CD_ATENDIMENTO ATE
FROM ATENDIME A,
     IT_AGENDA_CENTRAL IT,
     AGENDA_CENTRAL AC
WHERE A.TP_ATENDIMENTO = 'A'
AND A.DT_ATENDIMENTO BETWEEN '01-01-2015' AND '30-04-2015'
AND A.CD_MULTI_EMPRESA = 1
AND A.CD_ATENDIMENTO = IT.CD_ATENDIMENTO
AND IT.CD_AGENDA_CENTRAL = AC.CD_AGENDA_CENTRAL
AND IT.CD_IT_AGENDA_PAI IS NULL
)
)
AND TP.CD_TIP_MAR = A2.CD_TIP_MAR
AND A2.CD_ESPECIALID = E.CD_ESPECIALID
AND A2.TP_ATENDIMENTO = 'A'
AND A2.DT_ATENDIMENTO BETWEEN '01-01-2015' AND '30-04-2015'
AND A2.CD_MULTI_EMPRESA = 1
AND A2.CD_PRESTADOR = P.CD_PRESTADOR
ORDER BY ATE ASC
))