SELECT USU,
       MAX(DECODE(CD_FILA,8,TOTAL,0)) "PC",
       MAX(DECODE(CD_FILA,12,TOTAL,0)) "R",
       MAX(DECODE(CD_FILA,13,TOTAL,0)) "EX",
       MAX(DECODE(CD_FILA,14,TOTAL,0)) "ER",
       MAX(DECODE(CD_FILA,15,TOTAL,0)) "AR",
       MAX(DECODE(CD_FILA,16,TOTAL,0)) "CB",
       MAX(DECODE(CD_FILA,17,TOTAL,0)) "SF",
       MAX(DECODE(CD_FILA,18,TOTAL,0)) "R",
       MAX(DECODE(CD_FILA,19,TOTAL,0)) "A",
       MAX(DECODE(CD_FILA,20,TOTAL,0)) "SS",
       MAX(DECODE(CD_FILA,23,TOTAL,0)) "*CONSULTA*",
       MAX(DECODE(CD_FILA,18,TOTAL,0)) "*EXAME*"
       FROM(
SELECT DATA_ATEND,
       USU,
       CD_FILA,
       FILA,
       SUM(N_SENHA) "TOTAL"
       FROM(
SELECT S1.CD_TEMPO_PROCESSO,
       TO_CHAR(S1.DH_PROCESSO,'DD/MM/YYYY') "DATA_ATEND",
       S1.NM_USUARIO "USU",
       FS.CD_FILA_SENHA "CD_FILA",
       FS.DS_FILA "FILA",
       COUNT(*) "N_SENHA"
FROM SACR_TEMPO_PROCESSO S1,
     TRIAGEM_ATENDIMENTO TA,
     FILA_SENHA FS
WHERE S1.CD_TIPO_TEMPO_PROCESSO = 20
      AND TA.DS_OBSERVACAO_REMOVIDO IS NULL
      AND To_Date(S1.DH_PROCESSO,'DD/MM/YYYY') BETWEEN To_Date(:DT_INI,'DD/MM/YYYY') AND To_Date(:DT_FIN,'DD/MM/YYYY')
      AND S1.CD_TRIAGEM_ATENDIMENTO = TA.CD_TRIAGEM_ATENDIMENTO
      AND FS.CD_FILA_SENHA = TA.CD_FILA_SENHA
      AND TA.CD_MULTI_EMPRESA = 1
      GROUP BY S1.CD_TEMPO_PROCESSO,
               S1.DH_PROCESSO,
               S1.NM_USUARIO,
               FS.CD_FILA_SENHA,
               FS.DS_FILA
      ORDER BY S1.NM_USUARIO,FS.DS_FILA
      )
      GROUP BY DATA_ATEND,USU,CD_FILA,FILA
      ORDER BY 1,2,3,4
      )
      GROUP BY USU
      ORDER BY 1