SELECT DATA_ATEND,
       USU,
       MAX(DECODE(CD_FILA,8,TOTAL,0)) "PRIMEIRA CONSULTA",
       MAX(DECODE(CD_FILA,12,TOTAL,0)) "RETORNO",
       MAX(DECODE(CD_FILA,13,TOTAL,0)) "EXAMES",
       MAX(DECODE(CD_FILA,14,TOTAL,0)) "AGENDAR EXAME E RETORNO",
       MAX(DECODE(CD_FILA,15,TOTAL,0)) "AGENDAR RETORNO",
       MAX(DECODE(CD_FILA,16,TOTAL,0)) "CONSULTA BALCÃO",
       MAX(DECODE(CD_FILA,17,TOTAL,0)) "SESSÃO FISIOTERAPIA",
       MAX(DECODE(CD_FILA,18,TOTAL,0)) "REGULACAO",
       MAX(DECODE(CD_FILA,19,TOTAL,0)) "S.A.U",
       MAX(DECODE(CD_FILA,20,TOTAL,0)) "SERVIÇO SOCIAL",
       MAX(DECODE(CD_FILA,23,TOTAL,0)) "*CONSULTA*",
       MAX(DECODE(CD_FILA,18,TOTAL,0)) "*EXAME*"
       FROM(
SELECT DATA_ATEND,
       USU,
       CD_FILA,
       FILA,
       SUM(N_SENHA) "TOTAL"
       FROM(
SELECT S1.CD_TEMPO_PROCESSO,
       TO_CHAR(S1.DH_PROCESSO,'DD/MM/YYYY') "DATA_ATEND",
       S1.NM_USUARIO "USU",
       FS.CD_FILA_SENHA "CD_FILA",
       FS.DS_FILA "FILA",
       COUNT(*) "N_SENHA"
FROM SACR_TEMPO_PROCESSO S1,
     TRIAGEM_ATENDIMENTO TA,
     FILA_SENHA FS
WHERE S1.CD_TIPO_TEMPO_PROCESSO = 20
      AND TA.DS_OBSERVACAO_REMOVIDO IS NULL
      AND S1.DH_PROCESSO BETWEEN '01-06-2014' AND '30-06-2014'
      AND S1.CD_TRIAGEM_ATENDIMENTO = TA.CD_TRIAGEM_ATENDIMENTO
      AND FS.CD_FILA_SENHA = TA.CD_FILA_SENHA
      AND TA.CD_MULTI_EMPRESA = 1
      GROUP BY S1.CD_TEMPO_PROCESSO,
               S1.DH_PROCESSO,
               S1.NM_USUARIO,
               FS.CD_FILA_SENHA,
               FS.DS_FILA
      ORDER BY S1.NM_USUARIO,FS.DS_FILA
      )
      GROUP BY DATA_ATEND,USU,CD_FILA,FILA
      ORDER BY 1,2,3,4
      )
      GROUP BY DATA_ATEND,USU
      ORDER BY 1,2