SELECT P.NM_PRESTADOR PRESTADOR,
       D.CD_DEPARA_MV CD_MV,
       D.CD_DEPARA_INTEGRA CD_CROSS,
       (SELECT DS_ESPECIALID FROM ESPECIALID WHERE CD_ESPECIALID IN((SELECT CD_ESPECIALID FROM ATENDIME WHERE CD_ATENDIMENTO IN(SELECT MAX(CD_ATENDIMENTO) FROM ATENDIME WHERE CD_PRESTADOR = D.CD_DEPARA_MV)))) ESPECIALIDADE,
       (SELECT CD_ESPECIALID FROM ATENDIME WHERE CD_ATENDIMENTO IN(SELECT MAX(CD_ATENDIMENTO) FROM ATENDIME WHERE CD_PRESTADOR = D.CD_DEPARA_MV)) CD_ESPECIALID_MV,
       (SELECT MAX(DP.CD_DEPARA_INTEGRA) FROM MVINTEGRA.DEPARA DP WHERE DP.TP_DEPARA = 'ESPECIALIDADE' AND DP.CD_DEPARA_MV IN(SELECT CD_ESPECIALID FROM ATENDIME WHERE CD_ATENDIMENTO IN(SELECT MAX(CD_ATENDIMENTO) FROM ATENDIME WHERE CD_PRESTADOR = D.CD_DEPARA_MV))) CD_ESPECIALID_CROSS
FROM MVINTEGRA.DEPARA D,
     DBAMV.PRESTADOR P
WHERE D.TP_DEPARA = 'PRESTADOR'
AND P.CD_PRESTADOR = D.CD_DEPARA_MV
AND D.CD_MULTI_EMPRESA = 1
AND P.TP_SITUACAO = 'A'
ORDER BY 1 ASC