SELECT i.DT_AGENDA,
       TO_CHAR(i.HR_INICIO_AGENDA,'HH24:MI') HR_INICIO_AGENDA,
       i.CD_AGENDAMENTO_INTEGRA,
       i.CD_PACIENTE_INTEGRA, 
       i.NM_PACIENTE, 
       l.NM_SERVICO, 
       i.DS_ESPECIALIDADE, 
       i.NM_PRESTADOR, 
       i.DT_GERADO,
       i.DS_ERRO,
       i.CD_IMV_LOG_REQUISICAO
       FROM MVINTEGRA.IMV_AGENDAMENTO i, 
            MVINTEGRA.IMV_LOG_REQUISICAO l
            WHERE i.DT_GERADO 
            BETWEEN '13-04-2015'
            AND '28-04-2015'
            AND i.CD_IMV_LOG_REQUISICAO = l.CD_IMV_LOG_REQUISICAO
            AND l.NM_SERVICO = 'AGENDAMENTO_EXAME'
            AND l.SN_SUCESSO = 'N'
            AND i.DS_ERRO LIKE '%O EXAME INFORMADO%'
            ORDER BY i.DS_ERRO asc