SELECT DISTINCT(A.CD_ATENDIMENTO) "ATENDIMENTO",
P.NM_PACIENTE "NOME",
TO_CHAR(P.DT_NASCIMENTO,'DD/MM/YYYY') "NASCIMENTO",
trunc((months_between(sysdate, P.DT_NASCIMENTO))/12) "IDADE",
P.TP_SEXO "SEXO",
TO_CHAR(A.DT_ATENDIMENTO,'DD/MM/YYYY') "DATA ATENDIMENTO",
TO_CHAR(A.DT_ALTA_MEDICA,'DD/MM/YYYY') "ALTA MEDICA",
E.DS_ESPECIALID "ESPECIALIDADE",
A.CD_CID "COD CID",
C.DS_CID "DESCRIÇÃO CID",
TIP.DS_TIP_RES "MOTIVO ALTA",
P.DS_ENDERECO "RUA",
P.NR_ENDERECO "NUMERO",
P.NR_CEP "CEP",
P.NM_BAIRRO "BAIRRO",
CD.NM_CIDADE "CIDADE",
CD.CD_UF "ESTADO" 
FROM ATENDIME A,PACIENTE P,ESPECIALID E,CID C,CIDADE CD, TIP_RES TIP
WHERE DT_ATENDIMENTO BETWEEN '01-JAN-2010' AND '31-DEZ-2010'
AND A.CD_PACIENTE = P.CD_PACIENTE
AND A.CD_TIP_RES = TIP.CD_TIP_RES(+)
AND A.CD_CID = C.CD_CID(+) 
AND A.CD_ESPECIALID = E.CD_ESPECIALID
AND CD.CD_CIDADE = P.CD_CIDADE
AND A.CD_MULTI_EMPRESA = 1
AND TP_ATENDIMENTO = 'A'
ORDER BY A.CD_ATENDIMENTO;
