SELECT A.CD_ORI_ATE,
       ORI.DS_ORI_ATE,
       A.DT_ATENDIMENTO,
       A.CD_ATENDIMENTO,
       A.CD_PACIENTE,
       P.NM_PACIENTE,
       TO_CHAR(A.HR_ATENDIMENTO,'HH24:MI') HR_ATEND,
       C.NM_CONVENIO,
       PRE.CD_PRESTADOR,
       PRE.NM_PRESTADOR,
       A.NM_USUARIO CD_USUARIO,
       U.NM_USUARIO NM_USUARIO
FROM ATENDIME A,
     ORI_ATE ORI,
     PACIENTE P,
     CONVENIO C,
     DBASGU.USUARIOS U,
     PRESTADOR PRE
WHERE A.CD_MULTI_EMPRESA = 1
AND A.DT_ATENDIMENTO BETWEEN '15-09-2015' AND '16-09-2015'
--AND TO_DATE(A.DT_ATENDIMENTO,'DD/MM/YYYY') BETWEEN TO_DATE(:DT_INICIAL,'DD/MM/YYYY') AND TO_DATE(:DT_FINAL,'DD/MM/YYYY')
--AND A.DS_ORI_ATE LIKE Decode(:DS_ORI_ATE,'TODOS','%',:DS_ORI_ATE)
--AND P.NM_PRESTADOR LIKE Decode(:NM_PRESTADOR,'TODOS','%',:NM_PRESTADOR)
AND A.CD_ORI_ATE = ORI.CD_ORI_ATE
AND P.CD_PACIENTE = A.CD_PACIENTE
AND A.CD_CONVENIO = C.CD_CONVENIO
AND A.NM_USUARIO = U.CD_USUARIO
AND A.CD_PRESTADOR = PRE.CD_PRESTADOR
ORDER BY A.CD_ORI_ATE,A.CD_ATENDIMENTO