SELECT i.CD_IMV_AGENDAMENTO,
       i.cd_agendamento_integra,
       i.DT_AGENDA,
       to_char(i.hr_inicio_agenda,'hh24:mi'),
       i.NM_PRESTADOR PRESTADOR,
       l.NM_SERVICO,
       i.CD_PACIENTE_INTEGRA,
       i.NM_PACIENTE,
       i.DS_ESPECIALIDADE ESPECIALIDADE,
       i.DT_GERADO,
       i.DS_ERRO ERRO
FROM MVINTEGRA.IMV_AGENDAMENTO i,
     MVINTEGRA.IMV_LOG_REQUISICAO l
WHERE i.DT_GERADO BETWEEN '18-11-2014' AND '22-11-2014'
    AND i.CD_IMV_LOG_REQUISICAO = l.CD_IMV_LOG_REQUISICAO
    AND l.SN_SUCESSO = 'N'
    ORDER BY 1 asc
    
    SELECT * FROM MVINTEGRA.IMV_AGENDAMENTO
    
SELECT AC.DT_AGENDA,
       TO_CHAR(HR_AGENDA,'HH24:MM'),
       SD.DS_SER_DIS,
       PRES.NM_PRESTADOR,
       IT.NM_PACIENTE,
       IT.CD_USUARIO,
       IT.SN_ENCAIXE
FROM IT_AGENDA_CENTRAL IT,
     AGENDA_CENTRAL AC,
     PRESTADOR PRES,
     SER_DIS SD
WHERE IT.CD_AGENDA_CENTRAL = AC.CD_AGENDA_CENTRAL
      AND AC.DT_AGENDA BETWEEN '18-11-2014' AND '19-11-2014'
      AND SD.CD_SER_DIS = IT.CD_SER_DIS
      AND PRES.CD_PRESTADOR = AC.CD_PRESTADOR
      AND AC.CD_MULTI_EMPRESA = 1
      
      

