SELECT A.CD_ATENDIMENTO,
       A.CD_PRESTADOR,
       P.CD_PACIENTE,
       P.NM_PACIENTE,
       A.DT_ATENDIMENTO,
       A.CD_TIP_MAR,
       A.CD_TIP_RES,
       A.CD_TIPO_INTERNACAO,
       A.CD_ESPECIALID,
       A.CD_SER_DIS,
       A.CD_MULTI_EMPRESA,
       A.DT_ALTA_MEDICA
FROM PACIENTE P,
     ATENDIME A
WHERE P.CD_PACIENTE IN(
SELECT P.CD_PACIENTE
FROM ATENDIME A, PACIENTE P
WHERE A.DT_ALTA_MEDICA BETWEEN '01-04-2014' AND '11-07-2014'
AND A.CD_TIP_RES = 31
AND A.CD_ESPECIALID = 55
AND A.CD_MULTI_EMPRESA = 1
AND A.CD_PACIENTE = P.CD_PACIENTE
)
AND A.DT_ALTA_MEDICA BETWEEN '01-04-2014' AND '11-07-2014'
AND A.CD_PACIENTE = P.CD_PACIENTE
AND A.CD_ESPECIALID = 55
AND A.CD_MULTI_EMPRESA = 1
ORDER BY A.DT_ALTA_MEDICA

SELECT * FROM ESPECIALID

