A.CD_ATENDIMENTO,
       A.CD_PRESTADOR,
       P.CD_PACIENTE,
       P.NM_PACIENTE,
       A.DT_ATENDIMENTO,
       A.CD_TIP_RES,
       A.CD_ESPECIALID,
       A.CD_SER_DIS,
       A.CD_MULTI_EMPRESA,
       A.DT_ALTA_MEDICA
FROM PACIENTE P,
     ATENDIME A
WHERE P.CD_PACIENTE IN(
SELECT P.CD_PACIENTE
FROM ATENDIME A, PACIENTE P
WHERE A.DT_ALTA_MEDICA BETWEEN '01-04-2014' AND '11-07-2014'
AND A.CD_TIP_RES = 31
AND A.CD_ESPECIALID = 55
AND A.CD_MULTI_EMPRESA = 1
AND A.CD_PACIENTE = P.CD_PACIENTE
)
AND A.DT_ALTA_MEDICA BETWEEN '01-04-2014' AND '11-07-2014'
AND A.CD_PACIENTE = P.CD_PACIENTE
AND A.CD_ESPECIALID = 55
AND A.CD_MULTI_EMPRESA = 1
ORDER BY A.DT_ALTA_MEDICA


SELECT A.CD_ATENDIMENTO,
       PRES.NM_PRESTADOR,
       P.CD_PACIENTE,
       P.NM_PACIENTE,
       A.DT_ATENDIMENTO,
       TP.DS_TIP_RES,
       A.DT_ALTA_MEDICA,
       VDIC.NR_FAT
FROM ATENDIME A, PACIENTE P, VDIC_CADASTRAR_PEDIDO_IMAGEM VDIC, TIP_RES TP,PRESTADOR PRES
WHERE A.CD_PACIENTE = P.CD_PACIENTE
AND A.CD_PRESTADOR = PRES.CD_PRESTADOR
AND VDIC.ATENDIMENTO = A.CD_ATENDIMENTO
AND TP.CD_TIP_RES = A.CD_TIP_RES
AND A.DT_ATENDIMENTO BETWEEN '01-04-2014' AND '10-07-2014'
AND VDIC.SETOR_EXECUTANTE = 25
AND A.CD_MULTI_EMPRESA = 1
