--1º Atendimento
SELECT A.CD_PRESTADOR,
       A.CD_ATENDIMENTO,
       A.CD_PACIENTE,
       To_Char(A.DT_ATENDIMENTO,'DD/MM/YYYY'),
       P.NM_PACIENTE,
       RP.DS_RESPOSTA,
       LP.DS_LOC_PROCED
       FROM ATENDIME A,
            PACIENTE P,
            VDIC_RESPOSTA_DOCUMENTO VRD,
            REGISTRO_RESPOSTA RP,
            LOC_PROCED LP
       WHERE A.DT_ATENDIMENTO BETWEEN '01-04-2014' AND '11-07-2014'
       AND A.CD_ATENDIMENTO = VRD.ATENDIMENTO
       AND VRD.REGISTRO_DOCUMENTO = RP.CD_REGISTRO_DOCUMENTO
       AND A.CD_PACIENTE = P.CD_PACIENTE
       AND A.CD_ESPECIALID = 55
       AND A.CD_TIPO_INTERNACAO = 11
       AND RP.CD_PERGUNTA_DOC = 6247
       AND A.CD_LOC_PROCED = LP.CD_LOC_PROCED
       ORDER BY A.CD_ATENDIMENTO

--Lista de altas
SELECT A.CD_ATENDIMENTO,
       PRES.NM_PRESTADOR,
       P.CD_PACIENTE,
       P.NM_PACIENTE,
       A.DT_ATENDIMENTO,
       TP.DS_TIP_RES,
       A.DT_ALTA_MEDICA,
       VDIC.NR_FAT
FROM ATENDIME A, PACIENTE P, VDIC_CADASTRAR_PEDIDO_IMAGEM VDIC, TIP_RES TP,PRESTADOR PRES
WHERE A.CD_PACIENTE = P.CD_PACIENTE
AND A.CD_PRESTADOR = PRES.CD_PRESTADOR
AND VDIC.ATENDIMENTO = A.CD_ATENDIMENTO
AND TP.CD_TIP_RES = A.CD_TIP_RES
AND A.DT_ATENDIMENTO BETWEEN '01-04-2014' AND '10-07-2014'
AND VDIC.SETOR_EXECUTANTE = 25
AND A.CD_MULTI_EMPRESA = 1



--Lista de altas
SELECT INI.CD_PRESTADOR,
       INI.CD_ATENDIMENTO,
       INI.CD_PACIENTE,
       P.NM_PACIENTE,
       INI.DT_ATENDIMENTO,
       RP.DS_RESPOSTA,
       FIN.DT_ALTA_MEDICA
FROM ATENDIME FIN, ATENDIME INI, PACIENTE P, PRESTADOR PR, VDIC_RESPOSTA_DOCUMENTO VRD, REGISTRO_RESPOSTA RP
WHERE FIN.DT_ALTA_MEDICA BETWEEN '01-03-2014' AND '30-03-2014'
AND INI.CD_ATENDIMENTO = VRD.ATENDIMENTO
AND VRD.REGISTRO_DOCUMENTO = RP.CD_REGISTRO_DOCUMENTO
AND FIN.CD_PACIENTE = P.CD_PACIENTE
AND INI.CD_PACIENTE = P.CD_PACIENTE
AND FIN.CD_ESPECIALID = 55
--AND INI.CD_ESPECIALID = 55
AND FIN.CD_TIP_RES = 31
AND FIN.CD_MULTI_EMPRESA = 1
AND INI.CD_MULTI_EMPRESA = 1
AND INI.CD_TIP_MAR = 1
AND INI.CD_TIP_RES = 28
AND INI.CD_SER_DIS = 52
AND INI.CD_PRESTADOR IN(1401)
AND FIN.CD_PRESTADOR IN(1401)
AND RP.CD_PERGUNTA_DOC = 6247
AND INI.CD_PACIENTE = FIN.CD_PACIENTE
AND FIN.CD_PRESTADOR = PR.CD_PRESTADOR
AND INI.CD_PRESTADOR = PR.CD_PRESTADOR
--GROUP BY INI.CD_ATENDIMENTO,P.NM_PACIENTE, INI.DT_ATENDIMENTO,RP.DS_RESPOSTA,FIN.DT_ALTA_MEDICA
ORDER BY FIN.DT_ALTA_MEDICA

SELECT * FROM ESPECIALID WHERE CD_ESPECIALID = 40

SELECT * FROM ATENDIME WHERE CD_PACIENTE = 661315
AND CD_MULTI_EMPRESA =1
AND CD_ESPECIALID = 55
ORDER BY 1

SELECT * FROM TIPO_INTERNACAO
SELECT * FROM ORI_ATE

SELECT P.CD_PACIENTE,
       P.NM_PACIENTE,
       A.DT_ALTA_MEDICA,
       TP.DS_TIP_RES
FROM ATENDIME A, PACIENTE P, TIP_RES TP
WHERE A.DT_ALTA_MEDICA BETWEEN '01-03-2014' AND '30-03-2014'
AND A.CD_TIP_RES = TP.CD_TIP_RES
AND A.CD_MULTI_EMPRESA = 1
AND A.CD_PRESTADOR = 1401

AND A.CD_ESPECIALID = 55
AND A.CD_MULTI_EMPRESA = 1
AND A.CD_PRESTADOR = 1401
AND A.CD_PACIENTE = P.CD_PACIENTE
ORDER BY A.DT_ALTA_MEDICA

SELECT P.CD_PACIENTE,
       P.NM_PACIENTE,
       A.DT_ATENDIMENTO,
       A.CD_PROCEDIMENTO
FROM PACIENTE P, ATENDIME A
WHERE P.CD_PACIENTE IN(SELECT P.CD_PACIENTE
FROM ATENDIME A, PACIENTE P
WHERE A.DT_ALTA_MEDICA BETWEEN '01-03-2014' AND '30-03-2014'
AND A.CD_TIP_RES = 31
AND A.CD_ESPECIALID = 55
AND A.CD_MULTI_EMPRESA = 1
AND A.CD_PRESTADOR = 1401
AND A.CD_PACIENTE = P.CD_PACIENTE)
AND P.CD_PACIENTE = A.CD_PACIENTE
AND A.CD_TIP_MAR = 1
AND A.CD_ESPECIALID = 55
AND A.CD_MULTI_EMPRESA = 1
ORDER BY P.CD_PACIENTE


SELECT * FROM PROCEDIMENTO

SELECT *
FROM
PED_RX
WHERE CD_ATENDIMENTO = 2735738

SELECT * FROM
VDIC_CADASTRAR_PEDIDO_IMAGEM
WHERE ATENDIMENTO = 2735738

