SELECT TO_CHAR(RC.DT_CONTATO,'DD/MM/YYYY') DATA, TO_CHAR(RC.HR_CONTATO,'HH24:MI') HORA, RC.CD_USUARIO, RC.DS_ASSUNTO, RC.DS_CONTATO 
FROM IT_AGENDA_CENTRAL IT,
     AGENDA_CENTRAL AG,
     REGISTRO_CONTATO RC
WHERE IT.CD_AGENDA_CENTRAL = AG.CD_AGENDA_CENTRAL 
AND IT.CD_IT_AGENDA_CENTRAL = RC.CD_REGISTRO_VINCULADO