SELECT P.CD_PACIENTE CD,
       P.NM_PACIENTE NOME,
       P.NM_MAE MAE,
       p.NM_SOCIAL_PACIENTE,
       TO_CHAR(P.DT_NASCIMENTO,'DD/MM/YYYY') "NASCIMENTO",
       trunc((months_between(sysdate, P.DT_NASCIMENTO))/12) "IDADE",
       P.TP_SEXO "SEXO",
       P.NR_IDENTIDADE || '-' || P.DS_OM_IDENTIDADE RG,
       P.NR_CNS SUS,
       (SELECT SAME.NR_MATRICULA_SAME FROM SAME WHERE SAME.CD_PACIENTE = P.CD_PACIENTE AND SAME.CD_CAD_SAME = 1) PRONTUARIO
FROM PACIENTE P
     WHERE P.CD_PACIENTE = 1272011