SELECT VDIC_DOCUMENTO_PRONTUARIO.DESC_DOCUMENTO_PRONTUARIO, COUNT(*)
                                FROM VDIC_RESPOSTA_DOCUMENTO,
                                     VDIC_DOCUMENTO_PRONTUARIO,
                                     ATENDIME
                                WHERE ATENDIME.CD_ATENDIMENTO = VDIC_RESPOSTA_DOCUMENTO.ATENDIMENTO
                                AND ATENDIME.CD_MULTI_EMPRESA = 1
                                AND VDIC_RESPOSTA_DOCUMENTO.DOCUMENTO_PRONTUARIO IN(286,53,89,90,341,265)
                                AND TO_CHAR(ATENDIME.DT_ATENDIMENTO,'YYYY') = TO_CHAR(sysdate,'YYYY')
                                AND VDIC_DOCUMENTO_PRONTUARIO.DOCUMENTO_PRONTUARIO = VDIC_RESPOSTA_DOCUMENTO.DOCUMENTO_PRONTUARIO
                                GROUP BY VDIC_DOCUMENTO_PRONTUARIO.DESC_DOCUMENTO_PRONTUARIO