SELECT VIRD.DESC_RESPOSTA
FROM VDIC_ITEM_RESPOSTA_DOCUMENTO  VIRD
WHERE VIRD.REGISTRO_DOCUMENTO IN(
                                SELECT VDIC_RESPOSTA_DOCUMENTO.REGISTRO_DOCUMENTO 
                                FROM VDIC_RESPOSTA_DOCUMENTO,
                                     ATENDIME
                                WHERE ATENDIME.CD_ATENDIMENTO = VDIC_RESPOSTA_DOCUMENTO.ATENDIMENTO
                                AND ATENDIME.CD_MULTI_EMPRESA = 1
                                AND VDIC_RESPOSTA_DOCUMENTO.DOCUMENTO_PRONTUARIO IN(169)
                                AND ATENDIME.CD_ATENDIMENTO IN(3594723)
                             )
AND VIRD.PERGUNTA_DOCUMENTO IN(3741)
ORDER BY VIRD.DESC_RESPOSTA